# -*- coding: utf-8 -*-
"""data_sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goIbDidRFbnETfiA5UepQCDsOlUKyESX
"""

from datasets import load_dataset
import pandas as pd
import os
from tqdm import tqdm

"""# Datasets & Methods"""

''' True-false (Azariaa & Mitchell 2023) '''

class TrueFalseBuilder():
  def __init__(self):
    self.path = '/content/drive/My Drive/belief-repr-1/datasets/true-false'

  def get_dataset(self):
    dfs = []
    for file in tqdm(os.listdir(self.path), desc="Processing files"):
      if file.endswith('.csv'):
        df = pd.read_csv(os.path.join(self.path, file))
        df['filename'] = file
        dfs.append(df)
    df = pd.concat(dfs)
    return df

  def debug(self):
    print(os.listdir(self.path))

''' TruthfulQA (Lin et al. 2022) '''

class TruthfulQABuilder():
  def __init__(self):
    self.path = '/content/drive/My Drive/belief-repr-1/datasets/truthfulqa/TruthfulQA.csv'

  def get_dataset(self):
    return pd.read_csv(self.path)

''' MuLan (Fierro et al. 2024) '''

class MuLanBuilder():
  def __init__(self):
    self.json_dataset = load_dataset("coastalcph/fm_queries")

  def get_dataset(self):
    return self.json_dataset['train'].to_pandas()

''' True-false-easy '''

class TrueFalseEasyBuilder():
  def __init__(self):
    self.path = '/content/drive/My Drive/belief-repr-1/datasets/true-false-easy'

  def get_dataset(self):
    dfs = []
    for file in tqdm(os.listdir(self.path), desc="Processing files"):
      if file.endswith('.csv'):
        df = pd.read_csv(os.path.join(self.path, file))
        df['filename'] = file
        dfs.append(df)
    df = pd.concat(dfs)
    print("===================")
    print("WATCH OUT! Datapoints have different column entries depending on the csv")
    print()
    return df

  def debug(self):
    print(os.listdir(self.path))